### ISSUE TITLE
feature wish: lookahead without consuming token

### ISSUE THREAD

**Issue by hhugo** [let-def/menhir#1]
I know it's not the official repo but since you're experimenting ...

I've hacked around menhir to fill my need :
https://github.com/ocsigen/js_of_ocaml/blob/master/compiler/js_parser.mly#L202

**Comment by let-def** [comment]
What you would like is some way to specify in the input grammar that a token should be used to select a production but not discarded after that, right?

Eg.  `| s=statement_need_semi %dontconsume T_RCURLY {`

**Comment by hhugo** [comment]
right ! another alternative is to have something similar to `error` (ie: `next_token`) (cf `8. Error handling and recovery` from the manual `http://gallium.inria.fr/~fpottier/menhir/manual.pdf`)
Eg. `| s=statement_need_semi next_token {`

**Comment by let-def** [comment]
I was thinking of just introducing the keyword `$next_token` to have direct access to the look-ahead. This is just a small modification, does that still match your needs?

I had some hesitation, because its incompatible with another change introduced for merlin: follow reductions in a eager manner, so that if there is no need for a lookahead, the production is reduced before reading a new token.
This was introduced to help error diagnostic, but the two use-cases can be kept separate (e.g my modification only helps when dealing with "error" tokens) and I am not satisfied with my solution anyway.

**Comment by hhugo** [comment]
It matches my need if I can match on `$next_token` to decide whether or not the production is valid.

cross-ref https://github.com/ocsigen/js_of_ocaml/issues/154

**Comment by hhugo** [comment]
No longer needed
